AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 instance

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-arm64-ebs'
  InstancePoolSize:
    Type: Number
    Description: Number of EIPs to allocate. Limited for cost and demo reasons.
    Default: 1
    AllowedValues:
      - 1
      - 2

Conditions:
  CreateInstance2: !Equals
    - !Ref InstancePoolSize
    - 2
                                                   
Resources:
 Ec2Instance1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref LatestAmiId
      InstanceType: t4g.micro
      Tags:
        - Key: Name
          Value: EipRotatePocInstance1
        - Key: Group
          Value: EipRotatePocInstance    

 Ec2Instance2: 
    Condition: CreateInstance2
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref LatestAmiId
      InstanceType: t4g.micro
      Tags:
        - Key: Name
          Value: EipRotatePocInstance1
        - Key: Group
          Value: EipRotatePocInstance    

